### ISSUE TITLE
Plugin fails to initialize in PyCharm

### ISSUE THREAD

**Issue by grvhi** [a-iv/IntelliJ-Time-Tracker#1]
I've just downloaded this plugin and installed it in PyCharm using the "Install from disk" option. On restarting PyCharm I get an error that the plugin failed to initialise and will be disabled. This is with PyCharm 2.7.3 (build 129.782).

Any ideas as to how I can get it working?

Thanks

**Comment by a-iv** [comment]
@Erve1879 There is an issue in Darcula and IntelliJ themes.
They will cause `ArrayIndexOutOfBoundsException`.

**Comment by a-iv** [comment]
Fixed in d863769e932495091dd5f61629cbbf25e5dd253d.
